version: "3"
services:
  postgres:
    image: postgres:12.7
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=account
    ports:
      - "5432:5432"
